### PR TITLE
Add Postman schema

### PR DESCRIPTION
**Pull request by adrianwojdat**
Added link to Postman request schema

### CODE REVIEW

**Review by khrx64 — APPROVED** [review]
Looks OK :)

**Comment by richardtifelt** [comment]
Should we maybe write some text to explain it?

Would it be nice to have a link in the nav as well?

**Comment by adrianwojdat** [comment]
> Should we maybe write some text to explain it?
> 
> Would it be nice to have a link in the nav as well?

I added a section for postman so now we have a link in nav and some explanation of how to start and what we can do with that :D 
Screenshot 2021-01-04 at 10 39 07

**Comment by adrianwojdat** [comment]
Regarding feedback from Monday demo, I also added alert

Screenshot 2021-01-04 at 14 27 11

**Review by carlosdanna — APPROVED** [review]
LGTM!! Great job!

**Pull request merged**
